# Exported from Render on 2026-03-17T17:29:57Z
version: "1"
services:
- type: web
  name: Back-End-Ruan2.0
  runtime: docker
  repo: https://github.com/Ruan-Marcelo/Back-End-Ruan2.0
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
